//@ui5-bundle no/meriton/Home/Component-preload.js
jQuery.sap.registerPreloadedModules({
"version":"2.0",
"modules":{
	"no/meriton/Home/Component.js":function(){sap.ui.define(["sap/ui/core/UIComponent","sap/ui/Device","no/meriton/Home/model/models"],function(e,t,i){"use strict";return e.extend("no.meriton.Home.Component",{metadata:{manifest:"json"},init:function(){e.prototype.init.apply(this,arguments);this.getRouter().initialize();this.setModel(i.createDeviceModel(),"device")}})});
},
	"no/meriton/Home/controller/Main.controller.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller"],function(o){"use strict";return o.extend("no.meriton.Home.controller.Main",{onInit:function(){},onPressCv:function(o){window.location.href="/CV/"},onPressCovid19:function(o){window.location.href="/Covid19"},onPressQRBarcode:function(o){window.location.href="/QRBarcode"}})});
},
	"no/meriton/Home/i18n/i18n.properties":'title=Title\nappTitle=Home\nappDescription=App Description',
	"no/meriton/Home/i18n/i18n_en.properties":'title=Title\nappTitle=Covid19\nappDescription=App Description',
	"no/meriton/Home/i18n/i18n_no.properties":'title=Title\nappTitle=Covid19\nappDescription=App Description',
	"no/meriton/Home/manifest.json":'{"_version":"1.12.0","sap.app":{"id":"no.meriton.Home","type":"application","i18n":"i18n/i18n.properties","applicationVersion":{"version":"1.0.0"},"title":"{{appTitle}}","description":"{{appDescription}}","sourceTemplate":{"id":"ui5template.basicSAPUI5ApplicationProject","version":"1.40.12"}},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"config":{"fullWidth":true},"flexEnabled":false,"rootView":{"viewName":"no.meriton.Home.view.Main","type":"XML","async":true,"id":"Main"},"dependencies":{"minUI5Version":"1.65.6","libs":{"sap.f":{"minVersion":""},"sap.m":{},"sap.ui.core":{},"sap.ui.layout":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"no.meriton.Home.i18n.i18n"}}},"resources":{"css":[{"uri":"css/style.css"}]},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","async":true,"viewPath":"no.meriton.Home.view","controlAggregation":"pages","controlId":"app","clearControlAggregation":false},"routes":[{"name":"RouteMain","pattern":"RouteMain","target":["TargetMain"]}],"targets":{"TargetMain":{"viewType":"XML","transition":"slide","clearControlAggregation":false,"viewId":"Main","viewName":"Main"}}}}}',
	"no/meriton/Home/model/models.js":function(){sap.ui.define(["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,n){"use strict";return{createDeviceModel:function(){var i=new e(n);i.setDefaultBindingMode("OneWay");return i}}});
},
	"no/meriton/Home/view/Main.view.xml":'<mvc:View controllerName="no.meriton.Home.controller.Main" xmlns:mvc="sap.ui.core.mvc" xmlns:grid="sap.ui.layout.cssgrid" xmlns:f="sap.f"\n\tdisplayBlock="true" xmlns="sap.m"><Shell id="shell" appWidthLimited="false"><App id="app"><pages><Page showHeader="false" enableScrolling="false"><VBox class="sapUiSmallMargin centered"><f:GridContainer id="demoGrid" class="sapUiSmallMargin"><f:layout><f:GridContainerSettings rowSize="84px" columnSize="84px" gap="8px"/></f:layout><f:layoutXS><f:GridContainerSettings rowSize="70px" columnSize="70px" gap="8px"/></f:layoutXS><GenericTile id="oCv" header="Meriton Gashi" subheader="SAP / UX Consultant" press="onPressCv"><layoutData><f:GridContainerItemLayoutData minRows="2" columns="2"/></layoutData><TileContent footer="CV"><ImageContent src="sap-icon://employee-pane"/></TileContent></GenericTile><GenericTile header="Covid19" subheader="API Handling" press="onPressCovid19"><layoutData><f:GridContainerItemLayoutData minRows="2" columns="2"/></layoutData><TileContent footer="Application"><ImageContent src="sap-icon://geographic-bubble-chart"/></TileContent></GenericTile><GenericTile header="QR / Barcode" subheader="" press="onPressQRBarcode"><layoutData><f:GridContainerItemLayoutData minRows="2" columns="2"/></layoutData><TileContent footer="Application"><ImageContent src="sap-icon://bar-code"/></TileContent></GenericTile></f:GridContainer></VBox></Page></pages></App></Shell></mvc:View>'
}});
